title: Just the Docs introduction
description: Lorem ipsum
theme: just-the-docs

url: https://asiakostrzewa/just-the-docs-introduction

aux_links:
  Template Repository: https://github.com/asiakostrzewa/just-the-docs-introduction
